# Generated by Django 4.0.4 on 2022-05-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='alt_text',
            field=models.TextField(default='alt text', max_length=50),
            preserve_default=False,
        ),
    ]
