# Generated by Django 4.0.4 on 2022-05-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(default='dawdw'),
            preserve_default=False,
        ),
    ]
