# Generated by Django 4.0.4 on 2022-05-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_img_1_product_img_2_product_img_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
