# Generated by Django 4.0.4 on 2022-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_img_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
